server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ops?currentSchema=auth
    username: ops
    password: ops
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Flyway configuration
  flyway:
    enabled: true
    schemas: auth
    locations: classpath:db/migration
    baseline-on-migrate: true

  # การตั้งค่าสำหรับการส่งอีเมล
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  # การตั้งค่า Thymeleaf สำหรับเทมเพลตอีเมล
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html

jwt:
  secret: Q2POR7Mf/jft9Ul32R7jvtjylaSNQ+RM5UqlHT808okmOydt7RW9rDSO3RwXhKnQtja8ZZgI5Y+xd+aIVg5vOQ==
  expirationMs: 900000         # 15 minutes
  refreshExpirationMs: 604800000 # 7 days

# การตั้งค่าแอพพลิเคชัน
app:
  name: YIP E-INVENTORY
  version: 1.0.0
  description: ระบบจัดการคลังสินค้าและทรัพยากร

logging:
  level:
    root: INFO
    com.yipintsoi: DEBUG
    org.flywaydb: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
  instances:
    authServiceCircuitBreaker:
      slidingWindowSize: 10
      failureRateThreshold: 50
      permittedNumberOfCallsInHalfOpenState: 3