server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ops?currentSchema=notification
    username: ops
    password: ops
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

flyway:
  enabled: true
  schemas: notification
  locations: classpath:db/migration

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
  instances:
    notificationServiceCircuitBreaker:
      slidingWindowSize: 10
      failureRateThreshold: 50
      permittedNumberOfCallsInHalfOpenState: 3

# Kafka configuration for notification service
kafka:
  bootstrap-servers: localhost:9092

# RabbitMQ configuration
rabbitmq:
  host: localhost
  queue: notification-queue
