apiVersion: v1
kind: Service
metadata:
  name: audit-log-service
spec:
  selector:
    app: audit-log-service
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: ClusterIP
