apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-log-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audit-log-service
  template:
    metadata:
      labels:
        app: audit-log-service
    spec:
      containers:
        - name: audit-log-service
          image: audit-log-service:latest
          ports:
            - containerPort: 8088
          envFrom:
            - configMapRef:
                name: system-config
            - secretRef:
                name: system-secrets
