apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ocr-service
  template:
    metadata:
      labels:
        app: ocr-service
    spec:
      containers:
        - name: ocr-service
          image: ocr-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: system-config
            - secretRef:
                name: system-secrets
