apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workflow-service
  template:
    metadata:
      labels:
        app: workflow-service
    spec:
      containers:
        - name: workflow-service
          image: workflow-service:latest
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: system-config
            - secretRef:
                name: system-secrets
