version: '3.8'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    networks:
      - ops-network

  inventory-service:
    build: ./inventory-service
    ports:
      - "8082:8082"
    networks:
      - ops-network

  vehicle-service:
    build: ./vehicle-service
    ports:
      - "8083:8083"
    networks:
      - ops-network

  repair-service:
    build: ./repair-service
    ports:
      - "8084:8084"
    networks:
      - ops-network

  workflow-service:
    build: ./workflow-service
    ports:
      - "8085:8085"
    networks:
      - ops-network

  ocr-service:
    build: ./ocr-service
    ports:
      - "8000:8000"
    networks:
      - ops-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./ops/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - ops-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - ops-network

networks:
  ops-network:
    driver: bridge
