apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Parsers_File  parsers.conf
    [INPUT]
        Name         tail
        Path         /var/log/containers/*.log
        Parser       docker
        Tag          kube.*
    [FILTER]
        Name         kubernetes
        Match        kube.*
        Merge_Log    On
        Keep_Log     Off
    [OUTPUT]
        Name         loki
        Match        *
        Url          http://loki:3100/loki/api/v1/push
