apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: ops-services
data:
  application.properties: |
    spring.application.name=auth-service
    management.endpoints.web.exposure.include=health,info,prometheus
    spring.kafka.bootstrap-servers=kafka-service:9092
    app.force-single-session=true