server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ops?currentSchema=user
    username: ops
    password: ops
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

flyway:
  enabled: true
  schemas: user
  locations: classpath:db/migration

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
  instances:
    userServiceCircuitBreaker:
      slidingWindowSize: 10
      failureRateThreshold: 50
      permittedNumberOfCallsInHalfOpenState: 3

# Kafka configuration (ถ้ามีการใช้งาน event-driven ใน User Service)
kafka:
  bootstrap-servers: localhost:9092

# RabbitMQ configuration (ถ้ามี)
rabbitmq:
  host: localhost
  queue: user-service-queue

# Redis configuration (สำหรับ caching หรือ pub/sub)
