server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ops?currentSchema=repair
    username: ops
    password: ops
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

flyway:
  enabled: true
  schemas: repair
  locations: classpath:db/migration

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
  instances:
    repairServiceCircuitBreaker:
      slidingWindowSize: 10
      failureRateThreshold: 50
      permittedNumberOfCallsInHalfOpenState: 3
